/**
 * API client: typed shapes mirroring packages/api responses, fetch helpers,
 * and an SSE reader for POST /api/chat.
 */
import { imageVersionOf } from "./versions.js";

export interface Book {
  id: string;
  title: string;
  label: string;
  pageCount: number;
  printedToPdfOffset: number;
  /** sha256 prefix of the current PDF; changes when a retake replaces a page. */
  pdfRevision: string | null;
  /** "artbook": one spread per PDF page, page numbers are PDF pages and `spread` maps them to printed folios. */
  kind?: "guide" | "artbook";
  spread?: { pdfPage: number; leftFolio: number } | null;
}

export const isArtBook = (b: Book): boolean => b.kind === "artbook";

/** Printed folios shown on a PDF page of an art book ([left, right]); [] for the cover or a guide. */
export function spreadFolios(b: Book, pdfPage: number): number[] {
  const s = b.spread;
  if (!s || pdfPage < s.pdfPage || pdfPage > b.pageCount) return [];
  const left = s.leftFolio + 2 * (pdfPage - s.pdfPage);
  return [left, left + 1];
}

/** PDF page of an art book that shows a printed folio (either side of the spread), or null. */
export function spreadForFolio(b: Book, folio: number): number | null {
  const s = b.spread;
  if (!s || folio < s.leftFolio) return null;
  const pdfPage = s.pdfPage + Math.floor((folio - s.leftFolio) / 2);
  return pdfPage <= b.pageCount ? pdfPage : null;
}

/** How a viewer page is named: "p. 159" for a guide, "pp. 118–119" (or "cover") for an art book spread. */
export function pageLabel(b: Book, page: number): string {
  if (!isArtBook(b)) return "p. " + page;
  const f = spreadFolios(b, page);
  return f.length ? "pp. " + f[0] + "–" + f[1] : "cover";
}

export interface PageRef {
  book: string;
  page: number;
}

export interface ResolvedEntity {
  name: string;
  nameNorm: string;
  types: string[];
  pages: PageRef[];
  match: "exact" | "trigram" | "prior";
  similarity: number;
  matchedText: string;
  isLocation: boolean;
}

export interface Citation {
  book: string;
  page: number;
  quote: string | null;
  chunk_idx: number | null;
  heading_path: string | null;
  title: string | null;
  documentIndex: number | null;
  imageVersion?: string | null;
}

export interface AnchorsEvent {
  type: "anchors";
  entities: ResolvedEntity[];
  pages: PageRef[];
  ownPages: PageRef[];
  routeQuestion: boolean;
  consulted: PageRef[];
  /** "book:page" -> photo version for the consulted pages. */
  imageVersions?: Record<string, string>;
}

/** An artwork from an art book shown next to an answer (docs/build-spec-artbooks.md §7). */
export interface ArtItem {
  id: number;
  book: string;
  pdfPage: number;
  folios: number[];
  /** [x0, y0, x1, y1] as fractions of the spread. */
  bbox: [number, number, number, number];
  kind: string;
  name: string | null;
  /** caption: named from the printed caption; visual: identified from the picture; search: found by description. */
  source: "caption" | "visual" | "search";
  confidence: "high" | "medium" | "low";
  captionJa: string | null;
  description: string;
  imageVersion: string | null;
  subject: string | null;
  tier: number;
}

export interface AnswerStats {
  model: string;
  mode: string;
  fellBack: boolean;
  inputTokens: number;
  outputTokens: number;
  latencyMs: number;
  citations: number;
  documents: number;
}

export type ChatEvent =
  | AnchorsEvent
  | { type: "art"; items: ArtItem[] }
  | { type: "text"; text: string }
  | { type: "citation"; citation: Citation }
  | { type: "done"; stats: AnswerStats }
  | { type: "error"; message: string };

export interface TypeaheadHit {
  name: string;
  nameNorm: string;
  types: string[];
  book: string;
  pages: number[];
  score: number;
}

export interface ChatRequest {
  messages: { role: "user" | "assistant"; content: string }[];
  bookIds?: string[];
  priorEntities?: string[];
  /** Guide pages the question is about (a checklist item's pages). */
  focus?: { book: string; page: number }[];
}

const withVersion = (url: string, v: string | null | undefined): string => (v ? url + "?v=" + encodeURIComponent(v) : url);

/** An artwork cut from its spread, fitted inside w x w px; ?v= (the spread version) makes it immutable. */
export const artCropUrl = (id: number, version: string | null, w = 240): string =>
  "/api/artworks/" + id + "/crop?w=" + w + (version ? "&v=" + encodeURIComponent(version) : "");

/** The PDF at a revision: a new revision is a new URL, so pdf.js never mixes byte ranges of two files. */
export const pdfUrl = (book: string, revision: string | null): string => withVersion("/api/books/" + encodeURIComponent(book) + "/pdf", revision);
export const pageImageUrl = (book: string, page: number): string =>
  withVersion("/api/books/" + encodeURIComponent(book) + "/pages/" + page + "/image", imageVersionOf(book, page));
/** 240 px wide JPEG generated by the api on first request and cached. */
export const pageThumbUrl = (book: string, page: number): string =>
  withVersion("/api/books/" + encodeURIComponent(book) + "/pages/" + page + "/thumb", imageVersionOf(book, page));

/** Fired on any 401 from the api, so the auth context re-reads the session (it may have ended). */
export const UNAUTHORIZED_EVENT = "miriel:unauthorized";
/** Sent on every request that changes data; the api refuses cookie-authenticated writes without it. */
export const WRITE_HEADER = { "x-miriel": "1" } as const;

export function noteUnauthorized(res: Response): void {
  if (res.status === 401 && typeof window !== "undefined") window.dispatchEvent(new Event(UNAUTHORIZED_EVENT));
}

async function getJson<T>(url: string, signal?: AbortSignal): Promise<T> {
  const res = await fetch(url, { signal: signal ?? null });
  noteUnauthorized(res);
  if (!res.ok) throw new Error(await problemMessage(res));
  return (await res.json()) as T;
}

export async function problemMessage(res: Response): Promise<string> {
  try {
    const p = (await res.json()) as { title?: string; detail?: string };
    return (p.title ?? "Request failed") + (p.detail ? ": " + p.detail : "") + " (" + res.status + ")";
  } catch {
    return "Request failed (" + res.status + ")";
  }
}

export const fetchBooks = (): Promise<Book[]> => getJson<Book[]>("/api/books");

export interface ImageVersions {
  book: string;
  pdfRevision: string | null;
  /** printed page -> photo version */
  pages: Record<string, string>;
}

export const fetchImageVersions = (book: string): Promise<ImageVersions> =>
  getJson<ImageVersions>("/api/books/" + encodeURIComponent(book) + "/image-versions");

export function fetchEntities(q: string, book: string | undefined, signal: AbortSignal): Promise<TypeaheadHit[]> {
  const params = new URLSearchParams({ q });
  if (book) params.set("book", book);
  return getJson<TypeaheadHit[]>("/api/entities?" + params.toString(), signal);
}

/** POST /api/chat and yield parsed SSE events until the stream ends. */
export async function* streamChat(body: ChatRequest, signal: AbortSignal): AsyncGenerator<ChatEvent> {
  const res = await fetch("/api/chat", {
    method: "POST",
    headers: { "content-type": "application/json", accept: "text/event-stream", ...WRITE_HEADER },
    body: JSON.stringify(body),
    signal,
  });
  noteUnauthorized(res);
  if (!res.ok) throw new Error(await problemMessage(res));
  if (!res.body) throw new Error("The server returned no stream.");

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  for (;;) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    let sep = buffer.indexOf("\n\n");
    while (sep >= 0) {
      const block = buffer.slice(0, sep);
      buffer = buffer.slice(sep + 2);
      const ev = parseSseBlock(block);
      if (ev) yield ev;
      sep = buffer.indexOf("\n\n");
    }
  }
  const tail = parseSseBlock(buffer);
  if (tail) yield tail;
}

export function parseSseBlock(block: string): ChatEvent | null {
  let data = "";
  for (const line of block.split("\n")) {
    if (line.startsWith("data:")) data += line.slice(5).trimStart();
  }
  if (!data) return null;
  try {
    return JSON.parse(data) as ChatEvent;
  } catch {
    return null;
  }
}
